### ISSUE TITLE
Writing multibyte strings

### ISSUE THREAD

**Issue by middlebrain** [marcospassos/java-php-serializer#3]
The current implementation of `writeString` and maybe also `writeProperty` and `writeKey` has the problem, that the length `(s:<length>)` of multibyte strings is not written correctly. This results on the PHP side in `unserialize() [function.unserialize]: Error at offset ...`

Unfortunately, you must give the length of a serialized string in bytes instead of characters. However, the byte count depends on the character encoding.

When testing the serializer with a servlet I didn't immediately notice this, because the standard encoding of the output is ISO-8859-1 (one character is always one byte).  Only when switching to UTF-8 (`response. setCharacterEncoding("UTF-8"`) and using german umlauts the problem came up.

My instant fix for UTF-8 looks like this:

Writer.java:

```java
...
import static java.nio.charset.StandardCharsets.UTF_8;
...
    public void writeString(String value)
    {
        setState(state.value());

        buffer.append("s:");
        buffer.append(value.getBytes(UTF_8).length);
        buffer.append(":\"");
        buffer.append(value);
        buffer.append("\";");
    }
...
```
It would certainly be better if the desired character encoding could be given to the writer.

Translated with www.DeepL.com/Translator.

**Comment by marcospassos** [comment]
It's a bug indeed.

I'll make changes to the builder to allow specifying a default charset when creating the serializer. Also, I'll add a new parameter to `serializeString` allowing to define a custom charset as per value.

Please allow me a few days to release a new version with the fixes.

**Comment by marcospassos** [comment]
I just released the version 0.6.0 that covers this issue. Could you please check if it covers your use case?

You can check the full release description here:
https://github.com/marcospassos/java-php-serializer/releases/tag/0.6.0

I've also updated the docs to reflect the new feature:
https://github.com/marcospassos/java-php-serializer

**Comment by middlebrain** [comment]
It works like a charm now.

Thank you very match for your quick support.

**Comment by marcospassos** [comment]
Closing as the issue has been fixed.
